-- =============================================================================
-- ScholarAgent — Docker init pointer
--
-- Canonical baseline schema lives in:
--   migrations/001_initial_schema.sql
--
-- docker-compose.yml mounts that file into docker-entrypoint-initdb.d.
-- Do not duplicate DDL here — a second copy will drift from production.
-- =============================================================================
