import type { UserContext } from "@/lib/auth/types";

export type { UserContext };

export interface ChatMessage {
  role: "user" | "assistant" | "system" | "tool";
  content: string;
  createdAt?: string;
}

export type PlanStepTool = "tavily" | "pgvector" | "both" | "synthesize";

export interface PlanStep {
  id: string;
  description: string;
  // Which tool the researcher should invoke for this step. Generated by the
  // LLM planner; the researcher falls back to keyword matching if omitted.
  tool?: PlanStepTool;
  status: "pending" | "in_progress" | "completed" | "failed";
  result?: string;
}

export interface RetrievedContext {
  source: "tavily" | "pgvector";
  content: string;
  metadata?: Record<string, unknown>;
}

export interface AgentGraphState {
  messages: ChatMessage[];
  mission: string;
  plan: PlanStep[];
  gathered_context: RetrievedContext[];
  current_step_index: number;
  final_response?: string;
  user_context?: UserContext;
}
